version       = "0.5.4"
author        = "jmsapps"
license       = "MIT"
description   = "A reactive, client-side single-page application (SPA) renderer written in Nim."
packageName   = "ntml"
srcDir        = "src"
