/* Generated by the Nim Compiler v2.2.0 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555836 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555174 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555172 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555172 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555172.node = NNI33555172;
NTI33555174.base = NTI33555171;
NTI33555175.base = NTI33555171;
var NNI33555171 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555174, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555175, name: "up", sons: null}]};
NTI33555171.node = NNI33555171;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555171.base = NTI33555167;
NTI33555172.base = NTI33555171;
NTI134217741.base = NTI33555172;
NTI134217743.base = NTI134217741;
var NNI33555836 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555836.node = NNI33555836;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555172;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555172;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555172;
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
NTI134217742.base = NTI134217741;

function toJSStr(s_p0) {
  var result_33556911 = null;

    var res_33556965 = newSeq__system_u2508((s_p0).length);
    var i_33556966 = 0;
    var j_33556967 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556966 < (s_p0).length)) break Label2;
          var c_33556968 = s_p0[i_33556966];
          if ((c_33556968 < 128)) {
          res_33556965[j_33556967] = String.fromCharCode(c_33556968);
          i_33556966 += 1;
          }
          else {
            var helper_33556994 = newSeq__system_u2508(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556995 = c_33556968.toString(16);
                  if ((((code_33556995) == null ? 0 : (code_33556995).length) == 1)) {
                  helper_33556994.push("%0");;
                  }
                  else {
                  helper_33556994.push("%");;
                  }
                  
                  helper_33556994.push(code_33556995);;
                  i_33556966 += 1;
                  if ((((s_p0).length <= i_33556966) || (s_p0[i_33556966] < 128))) {
                  break Label3;
                  }
                  
                  c_33556968 = s_p0[i_33556966];
                }
            };
++excHandler;
            try {
            res_33556965[j_33556967] = decodeURIComponent(helper_33556994.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556965[j_33556967] = helper_33556994.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556967 += 1;
        }
    };
    if (res_33556965.length < j_33556967) { for (var i = res_33556965.length ; i < j_33556967 ; ++i) res_33556965.push(null); }
               else { res_33556965.length = j_33556967; };
    result_33556911 = res_33556965.join("");

  return result_33556911;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557318 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2866(ti_p2))) {
      result_33557318 = src_p1;
      }
      else {
        result_33557318 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557318 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557318 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557318 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557318 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557318, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557318 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557318 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557318 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557318[i] = nimCopy(result_33557318[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557318 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557318 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557318[i] = nimCopy(result_33557318[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557318 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557318 = src_p1;
      break;
    }

  return result_33557318;

}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2181(), NTI33554449);
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557358 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557358 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557358;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557353 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557353 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557353;

}

function modInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 % b_p1);
  

  
}

function absInt(a_p0) {
    var Temporary1;

  var result_33557134 = 0;

    if ((a_p0 < 0)) {
    Temporary1 = (a_p0 * (-1));
    }
    else {
    Temporary1 = a_p0;
    }
    
    result_33557134 = Temporary1;

  return result_33557134;

}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/times.nim", line: 0};
framePtr = F;
F.line = 1372;
F.filename = "times.nim";
if (globalThis.utcInstance_654313201 === undefined) {
  globalThis.utcInstance_654313201 = [null];
}
F.line = 1373;
if (globalThis.localInstance_654313202 === undefined) {
  globalThis.localInstance_654313202 = [null];
}
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/times.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module index", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/types/index.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module index", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/types/index.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module get", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/utils/get.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module get", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/utils/get.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module index", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/core/index.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module index", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/core/index.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ntml", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/ntml.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ntml", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/ntml.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function toInt__system_u1579(f_p0) {
    var Temporary1;

  var result_33556013 = 0;

  var F = {procname: "system.toInt", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1293;
    F.filename = "system.nim";
    if ((0.0 <= f_p0)) {
    Temporary1 = (((f_p0 + 0.5)) | 0);
    }
    else {
    Temporary1 = (((f_p0 - 0.5)) | 0);
    }
    
    result_33556013 = Temporary1;
  framePtr = F.prev;

  return result_33556013;

}

function toFloat__system_u1573(i_p0) {
  var result_33556007 = 0.0;

  var F = {procname: "system.toFloat", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1274;
    F.filename = "system.nim";
    result_33556007 = i_p0;
  framePtr = F.prev;

  return result_33556007;

}

function HEX2F__system_u1585(x_p0, y_p1) {
  var result_33556020 = 0.0;

  var F = {procname: "system./", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1322;
    F.filename = "system.nim";
    result_33556020 = (toFloat__system_u1573(x_p0) / toFloat__system_u1573(y_p1));
  framePtr = F.prev;

  return result_33556020;

}

function epochTime__pureZtimes_u4458() {
  var result_654315883 = 0.0;

  var F = {procname: "times.epochTime", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/times.nim", line: 0};
  framePtr = F;
    F.line = 2792;
    F.filename = "times.nim";
    result_654315883 = HEX2F__system_u1585(new Date().getTime(), 1000);
  framePtr = F.prev;

  return result_654315883;

}

function newSeq__system_u2508(len_p0) {
  var result_33556944 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 635;
    F.filename = "system.nim";
    result_33556944 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556944[i] = null; }  framePtr = F.prev;

  return result_33556944;

}

function add__system_u1943(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function isFatPointer__system_u2866(ti_p0) {
  var result_33557300 = false;

  BeforeRet: {
    result_33557300 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557300;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function auxWriteStackTrace__system_u2085(f_p0) {
  var result_33556519 = [[]];

    var it_33556527 = f_p0;
    var i_33556528 = 0;
    var total_33556529 = 0;
    var tempFrames_33556530 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555836);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556527 == null)) && (i_33556528 <= 63))) break Label2;
          tempFrames_33556530[i_33556528].Field0 = it_33556527.procname;
          tempFrames_33556530[i_33556528].Field1 = it_33556527.line;
          tempFrames_33556530[i_33556528].Field2 = it_33556527.filename;
          i_33556528 += 1;
          total_33556529 += 1;
          it_33556527 = it_33556527.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556527 == null))) break Label4;
          total_33556529 += 1;
          it_33556527 = it_33556527.prev;
        }
    };
    result_33556519[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556529 == i_33556528))) {
    result_33556519[0].push.apply(result_33556519[0], [40]);;
    result_33556519[0].push.apply(result_33556519[0], HEX24__systemZdollars_u8((total_33556529 - i_33556528)));;
    result_33556519[0].push.apply(result_33556519[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556563 = 0;
      var colontmp__520093917 = 0;
      colontmp__520093917 = (i_33556528 - 1);
      var res_520093919 = colontmp__520093917;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_520093919)) break Label7;
            j_33556563 = res_520093919;
            result_33556519[0].push.apply(result_33556519[0], cstrToNimstr(tempFrames_33556530[j_33556563].Field2));;
            if ((0 < tempFrames_33556530[j_33556563].Field1)) {
            result_33556519[0].push.apply(result_33556519[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556519, 0, tempFrames_33556530[j_33556563].Field1);
            if (false) {
            result_33556519[0].push.apply(result_33556519[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556519, 0, 0);
            }
            
            result_33556519[0].push.apply(result_33556519[0], [41]);;
            }
            
            result_33556519[0].push.apply(result_33556519[0], [32,97,116,32]);;
            add__system_u1943(result_33556519, 0, tempFrames_33556530[j_33556563].Field0);
            result_33556519[0].push.apply(result_33556519[0], [10]);;
            res_520093919 -= 1;
          }
      };
    };

  return result_33556519[0];

}

function rawWriteStackTrace__system_u2181() {
  var result_33556614 = [];

    if (!((framePtr == null))) {
    result_33556614 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2085(framePtr)), NTI33554449);
    }
    else {
      result_33556614 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556614;

}

function unhandledException(e_p0) {
    var buf_33556659 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556659[0].push.apply(buf_33556659[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556659[0].push.apply(buf_33556659[0], e_p0.message);;
    }
    else {
    buf_33556659[0].push.apply(buf_33556659[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556659[0].push.apply(buf_33556659[0], [32,91]);;
    add__system_u1943(buf_33556659, 0, e_p0.name);
    buf_33556659[0].push.apply(buf_33556659[0], [93,10]);;
    buf_33556659[0].push.apply(buf_33556659[0], rawWriteStackTrace__system_u2181());;
    var cbuf_33556660 = toJSStr(buf_33556659[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556660);
  }
  else {
    throw cbuf_33556660;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 44;
    F.filename = "digitsutils.nim";
    var old_301990096 = (result_p0[result_p0_Idx]).length;
    F.line = 45;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      F.line = 47;
      var iHEX60gensym4_301990110 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520093912 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_520093912 < n_p3)) break Label4;
            F.line = 50;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990110 = i_520093912;
            F.line = 47;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990110), 0, (x_p1).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520093912 = addInt(i_520093912, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 56;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 112;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 116;
    F.filename = "digitsutils.nim";
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));
  framePtr = F.prev;

  
}

function HEX24__systemZdollars_u8(x_p0) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    F.filename = "dollars.nim";
    addInt__stdZprivateZdigitsutils_u241(result_369098762, 0, x_p0);
  framePtr = F.prev;

  return result_369098762[0];

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u8(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u8(a_p1),[32,46,46,32],HEX24__systemZdollars_u8(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal__stdZassertions_u45(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u43(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u45(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u85(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u43(msg_p0);
  framePtr = F.prev;

  
}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");

  
}

function nsuIntToStr(x_p0, minchars_p1) {
  var result_671089490 = [];

  var F = {procname: "strutils.intToStr", prev: framePtr, filename: "/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1144;
    F.filename = "strutils.nim";
    result_671089490 = nimCopy(null, HEX24__systemZdollars_u8(absInt(x_p0)), NTI33554449);
    Label1: {
      F.line = 1145;
      var i_671089495 = 0;
      F.line = 81;
      F.filename = "iterators_1.nim";
      var colontmp__520093922 = 0;
      F.line = 1145;
      F.filename = "strutils.nim";
      colontmp__520093922 = subInt(minchars_p1, (result_671089490).length);
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_520093923 = 1;
      Label2: {
        F.line = 97;
          Label3: while (true) {
          if (!(res_520093923 <= colontmp__520093922)) break Label3;
            F.line = 1145;
            F.filename = "strutils.nim";
            i_671089495 = res_520093923;
            F.line = 1146;
            result_671089490 = nimCopy(null, [48].concat(result_671089490), NTI33554449);
            F.line = 102;
            F.filename = "iterators_1.nim";
            res_520093923 = addInt(res_520093923, 1);
          }
      };
    };
    if ((x_p0 < 0)) {
    F.line = 1148;
    F.filename = "strutils.nim";
    result_671089490 = nimCopy(null, [45].concat(result_671089490), NTI33554449);
    }
    
  framePtr = F.prev;

  return result_671089490;

}

function App__main_u21() {
    var Temporary4;

  var result_520093718 = [];

  var F = {procname: "main.App", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/core/index.nim", line: 0};
  framePtr = F;
    F.line = 10;
    F.filename = "main.nim";
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 11;
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 12;
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 12;
    result_520093718.push.apply(result_520093718, [60,104,49,62]);;
    F.line = 12;
    result_520093718.push.apply(result_520093718, [70,101,97,116,117,114,101,100,32,112,114,111,112,101,114,116,105,101,115]);;
    F.line = 12;
    result_520093718.push.apply(result_520093718, [60,47,104,49,62]);;
    F.line = 14;
    result_520093718.push.apply(result_520093718, [60,117,108,62]);;
    F.line = 14;
    result_520093718.push.apply(result_520093718, [60,108,105,62]);;
    F.line = 14;
    result_520093718.push.apply(result_520093718, [80,114,111,112,101,114,116,121,32,49]);;
    F.line = 14;
    result_520093718.push.apply(result_520093718, [60,47,108,105,62]);;
    F.line = 15;
    result_520093718.push.apply(result_520093718, [60,108,105,62]);;
    F.line = 15;
    result_520093718.push.apply(result_520093718, [80,114,111,112,101,114,116,121,32,50]);;
    F.line = 15;
    result_520093718.push.apply(result_520093718, [60,47,108,105,62]);;
    F.line = 13;
    result_520093718.push.apply(result_520093718, [60,47,117,108,62]);;
    F.line = 11;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
    if (isAddClientReviews_520093700) {
    F.line = 18;
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 18;
    result_520093718.push.apply(result_520093718, [60,104,49,62]);;
    F.line = 18;
    result_520093718.push.apply(result_520093718, [67,108,105,101,110,116,32,114,101,118,105,101,119,115]);;
    F.line = 18;
    result_520093718.push.apply(result_520093718, [60,47,104,49,62]);;
    F.line = 20;
    result_520093718.push.apply(result_520093718, [60,117,108,62]);;
    F.line = 20;
    result_520093718.push.apply(result_520093718, [60,108,105,62]);;
    F.line = 20;
    result_520093718.push.apply(result_520093718, [82,101,118,105,101,119,32,49]);;
    F.line = 20;
    result_520093718.push.apply(result_520093718, [60,47,108,105,62]);;
    F.line = 21;
    result_520093718.push.apply(result_520093718, [60,108,105,62]);;
    F.line = 21;
    result_520093718.push.apply(result_520093718, [82,101,118,105,101,119,32,50]);;
    F.line = 21;
    result_520093718.push.apply(result_520093718, [60,47,108,105,62]);;
    F.line = 19;
    result_520093718.push.apply(result_520093718, [60,47,117,108,62]);;
    F.line = 17;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
    }
    
    F.line = 23;
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 23;
    result_520093718.push.apply(result_520093718, [60,104,49,62]);;
    F.line = 23;
    result_520093718.push.apply(result_520093718, [65,32,108,105,116,116,108,101,32,97,98,111,117,116,32,109,101,46,46,46]);;
    F.line = 23;
    result_520093718.push.apply(result_520093718, [60,47,104,49,62]);;
    F.line = 24;
    result_520093718.push.apply(result_520093718, [60,112,62]);;
    F.line = 24;
    result_520093718.push.apply(result_520093718, makeNimstrLit("With nearly two decades of experience as both a business owner and investor..."));;
    F.line = 24;
    result_520093718.push.apply(result_520093718, [60,47,112,62]);;
    F.line = 25;
    result_520093718.push.apply(result_520093718, [60,112,62]);;
    F.line = 25;
    result_520093718.push.apply(result_520093718, makeNimstrLit("Throughout the years, I\xE2\x80\x99ve strategically invested in and managed a portfolio of rental properties..."));;
    F.line = 25;
    result_520093718.push.apply(result_520093718, [60,47,112,62]);;
    F.line = 26;
    result_520093718.push.apply(result_520093718, [60,112,62]);;
    F.line = 26;
    result_520093718.push.apply(result_520093718, makeNimstrLit("Beyond my professional pursuits, I am a devoted father to two beautiful daughters..."));;
    F.line = 26;
    result_520093718.push.apply(result_520093718, [60,47,112,62]);;
    F.line = 27;
    result_520093718.push.apply(result_520093718, [60,112,62]);;
    F.line = 27;
    result_520093718.push.apply(result_520093718, makeNimstrLit("Combining my personal experiences as a parent with my expertise as a business owner..."));;
    F.line = 27;
    result_520093718.push.apply(result_520093718, [60,47,112,62]);;
    F.line = 28;
    result_520093718.push.apply(result_520093718, [60,112,62]);;
    F.line = 28;
    result_520093718.push.apply(result_520093718, [80,97,115,115,105,111,110,32,105,115,32,116,104,101,32,100,114,105,118,105,110,103,32,102,111,114,99,101,32,98,101,104,105,110,100,32,97,108,108,32,116,104,97,116,32,73,32,100,111,46,46,46]);;
    F.line = 28;
    result_520093718.push.apply(result_520093718, [60,47,112,62]);;
    F.line = 22;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
    F.line = 30;
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 31;
    result_520093718.push.apply(result_520093718, [60,104,49,62]);;
    F.line = 31;
    result_520093718.push.apply(result_520093718, [67,111,110,116,97,99,116]);;
    F.line = 30;
    result_520093718.push.apply(result_520093718, [60,47,104,49,62]);;
    F.line = 33;
    result_520093718.push.apply(result_520093718, [60,98,117,116,116,111,110,32,111,110,99,108,105,99,107,61,34,104,97,110,100,108,101,65,108,101,114,116,40,41,34,62]);;
    F.line = 33;
    result_520093718.push.apply(result_520093718, [83,117,98,109,105,116]);;
    F.line = 32;
    result_520093718.push.apply(result_520093718, [60,47,98,117,116,116,111,110,62]);;
    F.line = 29;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
    F.line = 10;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
    F.line = 9;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
    F.line = 35;
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 36;
    result_520093718.push.apply(result_520093718, [60,117,108,62]);;
    Label1: {
      F.line = 36;
      var iHEX60gensym2_520093799 = [];
      F.line = 247;
      F.filename = "iterators.nim";
      var colontmp__520093903 = [];
      F.line = 36;
      F.filename = "main.nim";
      colontmp__520093903 = [[116,104,105,115], [105,115], [97], [108,105,115,116]];
      F.line = 249;
      F.filename = "iterators.nim";
      var i_520093905 = 0;
      F.line = 250;
      var L_520093906 = (colontmp__520093903).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_520093905 < L_520093906)) break Label3;
            F.line = 36;
            F.filename = "main.nim";
            iHEX60gensym2_520093799 = colontmp__520093903[chckIndx(i_520093905, 0, (colontmp__520093903).length - 1)];
            F.line = 37;
            result_520093718.push.apply(result_520093718, [60,108,105,62]);;
            F.line = 37;
            result_520093718.push.apply(result_520093718, iHEX60gensym2_520093799);;
            F.line = 37;
            result_520093718.push.apply(result_520093718, [60,47,108,105,62]);;
            F.line = 13;
            F.filename = "iterators.nim";
            i_520093905 += 1;
            if (!(((colontmp__520093903).length == L_520093906))) {
            F.line = 254;
            failedAssertImpl__stdZassertions_u85(makeNimstrLit("/home/jeff/.choosenim/toolchains/nim-2.2.0/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    F.line = 35;
    F.filename = "main.nim";
    result_520093718.push.apply(result_520093718, [60,47,117,108,62]);;
    F.line = 39;
    result_520093718.push.apply(result_520093718, [60,100,105,118,62]);;
    F.line = 39;
    if ((modInt(currentTime_520093701, 2) == 0)) {
    Temporary4 = ([101,118,101,110,32,115,101,99,111,110,100,115,58,32]).concat(nsuIntToStr(currentTime_520093701, 1));
    }
    else {
    Temporary4 = ([111,100,100,32,115,101,99,111,110,100,115,58,32]).concat(nsuIntToStr(currentTime_520093701, 1));
    }
    
    result_520093718.push.apply(result_520093718, Temporary4);;
    F.line = 38;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
    F.line = 34;
    result_520093718.push.apply(result_520093718, [60,47,100,105,118,62]);;
  framePtr = F.prev;

  return result_520093718;

}

function renderApp__main_u121() {
  var F = {procname: "main.renderApp", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/examples/main.nim", line: 0};
  framePtr = F;
    F.line = 56;
    F.filename = "main.nim";
    var rootElement_520093818 = document.createElement("div");
    F.line = 57;
    rootElement_520093818.innerHTML = toJSStr(App__main_u21());
    F.line = 58;
    document.body.appendChild(rootElement_520093818);
  framePtr = F.prev;

  
}

function onDOMContentLoaded__main_u155(e_p0) {
  var F = {procname: "main.onDOMContentLoaded", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/examples/main.nim", line: 0};
  framePtr = F;
    F.line = 62;
    F.filename = "main.nim";
    renderApp__main_u121();
  framePtr = F.prev;

  
}
var Temporary1;
var F = {procname: "module main", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/examples/main.nim", line: 0};
framePtr = F;
F.line = 5;
F.filename = "main.nim";
var isAddClientReviews_520093700 = false;
F.line = 6;
var currentTime_520093701 = toInt__system_u1579(epochTime__pureZtimes_u4458());
F.line = 49;
rawEcho([67,111,109,112,105,108,105,110,103,32,102,111,114,32,74,97,118,97,83,99,114,105,112,116]);
F.line = 53;
function handleAlert() { window.alert('window, Hello, this is a custom alert!');}
F.line = 64;
Temporary1 = onDOMContentLoaded__main_u155.bind(null); Temporary1.ClP_0 = onDOMContentLoaded__main_u155; Temporary1.ClE_0 = null;
document.addEventListener("DOMContentLoaded", Temporary1, false);
F.line = 73;
rawEcho(App__main_u21());
framePtr = F.prev;
var F = {procname: "module main", prev: framePtr, filename: "/home/jeff/jmsapps/NTML/src/examples/main.nim", line: 0};
framePtr = F;
framePtr = F.prev;
